#Workflow name
name: CI/CD Pipeline

env:
  VERSION: '17'

on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.VERSION }}
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven And skip tests
        run: mvn --batch-mode --update-snapshots verify -DskipTests

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2


  #Test's job
  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Unit tests
        run: mvn verify -PunitTests

      - name: Run Integration tests
        run: mvn verify -PintegrationTests

      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1

      #Run Tests
      #- name: Run Tests
     #   run: mvn -B test