#Workflow name
name: CI/CD Pipeline

env:
  VERSION: '17'

on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.VERSION }}
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven And skip tests
        run: mvn --batch-mode --update-snapshots verify -DskipTests


  #Test's job
  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Unit tests
        run: mvn verify -PunitTests

      - name: Unit Test Report
        uses: phoenix-actions/test-reporting@v8
        id: test-report               # Set ID reference for step
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Integration Test Report           # Name of the check run which will be created
          path: reports/unit-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results

      - name: Run Integration tests
        run: mvn verify -PintegrationTests

      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1

      - name: Integration Test Report
        uses: phoenix-actions/test-reporting@v8
        id: test-report               # Set ID reference for step
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Integration Test Report         # Name of the check run which will be created
          path: reports/integration-*.xml    # Path to test results
          reporter: jest-junit        # Format of test results


      #Run Tests
      #- name: Run Tests
     #   run: mvn -B test